### ISSUE TITLE
🐞 Build error in Xcode: Symbols not found

### ISSUE THREAD

**Issue by Cotters** [godot-sdk-integrations/godot-inapp-review#10]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues
- [x] I have searched the discussions
- [x] I have starred the repository

### Current Behavior

Compile time error:
```
Undefined symbols for architecture arm64:
  "Object::_to_string()", referenced from:
      vtable for InappReviewPlugin in InappReviewPlugin.a[2](inapp_review_plugin.o)
  "Object::assign_type_static(GDType**, char const*, GDType const*)", referenced from:
      InappReviewPlugin::_get_property_listv(List<PropertyInfo, DefaultAllocator>*, bool) const in InappReviewPlugin.a[2](inapp_review_plugin.o)
      InappReviewPlugin::_get_property_listv(List<PropertyInfo, DefaultAllocator>*, bool) const in InappReviewPlugin.a[2](inapp_review_plugin.o)
      InappReviewPlugin::initialize_class() in InappReviewPlugin.a[2](inapp_review_plugin.o)
      _OUTLINED_FUNCTION_1 in InappReviewPlugin.a[2](inapp_review_plugin.o)
  "Object::_add_class_to_classdb(GDType const&, GDType const*)", referenced from:
      InappReviewPlugin::initialize_class() in InappReviewPlugin.a[2](inapp_review_plugin.o)
  "Object::get_signal_connection_flags(StringName const&, Callable const&) const", referenced from:
      vtable for InappReviewPlugin in InappReviewPlugin.a[2](inapp_review_plugin.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Expected Behavior

App should build and launch.

### Steps To Reproduce

1. Installed via AssetLib.
2. Export with plugin enabled both in Project setting and iOS build setting.
3. Build project in Xcode.
4. (Disabling the plugin fixes the issue.)

### Godot Version

4.5.1.stable

### OS Godot Is Running On

macOS 15

### Plugin Version

5.2

### OS Plugin Is Running On

iOS 26.x

**Comment by cengiz-pz** [comment]
@Cotters, [the 5.2 release](https://github.com/godot-mobile-plugins/godot-inapp-review/releases/tag/v5.2) requires a minimum Godot version of 4.6 due to [breaking iOS changes](https://github.com/godotengine/godot/pull/109974) included in Godot 4.6.  Use [release 5.1](https://github.com/godot-mobile-plugins/godot-inapp-review/releases/tag/v5.1) if you you need to work with Godot 4.5.1.

**Comment by Cotters** [comment]
I see! Thanks for the quick response on this. I'll update.

**Comment by Cotters** [comment]
@cengiz-pz I updated Godot to 4.6 however I'm seeing similar build errors - pasted below.

I ended up just using 4.5.1 and downloading release 5.1 of InAppReview which now works, thanks!

```
Undefined symbols for architecture arm64:
  "Object::_add_class_to_classdb(StringName const&, StringName const&)", referenced from:
      GameCenter::initialize_class() in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
  "Object::assign_class_name_static(Span<char> const&, StringName&)", referenced from:
      GameCenter::_get_property_listv(List<PropertyInfo, DefaultAllocator>*, bool) const in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
      GameCenter::_get_property_listv(List<PropertyInfo, DefaultAllocator>*, bool) const in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
      _OUTLINED_FUNCTION_18 in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
  "String::append_utf8(char const*, int, bool)", referenced from:
      ____ZN10GameCenter32request_achievement_descriptionsEv_block_invoke in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
      ____ZN10GameCenter32request_achievement_descriptionsEv_block_invoke in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
      ____ZN10GameCenter32request_achievement_descriptionsEv_block_invoke in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
      ____ZN10GameCenter32request_achievement_descriptionsEv_block_invoke in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
      ____ZN10GameCenter20request_achievementsEv_block_invoke in libgamecenter.arm64-ios.release_debug.a[3](game_center.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cengiz-pz** [comment]
@Cotters, this plugin does not use `GameKit.framework`, which `GameCenter` is a part of.  Could the above-mentioned errors be caused by another plugin that you are using?

**Comment by cengiz-pz** [comment]
Closing due to inactivity. Feel free to reopen if this is still relevant.
